[0m18:08:08.160060 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DE94705F40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DE94704620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DE947069C0>]}


============================== 18:08:08.197789 | 05009500-99de-4478-9d17-802d696a38df ==============================
[0m18:08:08.197789 [info ] [MainThread]: Running with dbt=1.7.14
[0m18:08:08.201347 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\cmotte\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt test', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m18:08:08.204347 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\cmotte\DVF_data\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:08:08.215438 [debug] [MainThread]: Command `dbt test` failed at 18:08:08.214152 after 0.42 seconds
[0m18:08:08.217499 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DE9453B2F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DE936E0770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DE94614D10>]}
[0m18:08:08.220067 [debug] [MainThread]: Flushing usage events
[0m18:08:08.257041 [debug] [MainThread]: Error sending anonymous usage statistics. Disabling tracking for this execution. If you wish to permanently disable tracking, see: https://docs.getdbt.com/reference/global-configs#send-anonymous-usage-stats.
[0m04:45:15.915270 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000264547A3350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000264547A27B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000264547A0AD0>]}


============================== 04:45:15.922148 | 2715163f-b45b-40e8-998a-c042887bf0ad ==============================
[0m04:45:15.922148 [info ] [MainThread]: Running with dbt=1.7.10
[0m04:45:15.924181 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\cmotte\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt test', 'send_anonymous_usage_stats': 'True'}
[0m04:45:15.925248 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\cmotte\dbt_for_dvf\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m04:45:15.928290 [debug] [MainThread]: Command `dbt test` failed at 04:45:15.928290 after 0.19 seconds
[0m04:45:15.929284 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000264545FD340>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000264545AB6B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002645469E3F0>]}
[0m04:45:15.929284 [debug] [MainThread]: Flushing usage events
[0m04:45:15.946947 [debug] [MainThread]: Error sending anonymous usage statistics. Disabling tracking for this execution. If you wish to permanently disable tracking, see: https://docs.getdbt.com/reference/global-configs#send-anonymous-usage-stats.
[0m13:20:08.716313 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015E3C9A21E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015E3C9A1D00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015E3C9A06B0>]}


============================== 13:20:08.725936 | b0f6f29b-4257-4077-ad41-cc0a200f21dd ==============================
[0m13:20:08.725936 [info ] [MainThread]: Running with dbt=1.7.10
[0m13:20:08.725936 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\cmotte\\.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt test', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:20:08.730413 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\cmotte\dbt_for_dvf\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:20:08.734243 [debug] [MainThread]: Command `dbt test` failed at 13:20:08.734243 after 0.18 seconds
[0m13:20:08.734243 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015E3C8669F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015E3C7F98E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015E3C7AE4B0>]}
[0m13:20:08.740274 [debug] [MainThread]: Flushing usage events
[0m13:20:08.765536 [debug] [MainThread]: Error sending anonymous usage statistics. Disabling tracking for this execution. If you wish to permanently disable tracking, see: https://docs.getdbt.com/reference/global-configs#send-anonymous-usage-stats.
[0m06:40:55.561530 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002275A4A2C90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002275A289EE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002275A4A1D90>]}


============================== 06:40:55.582171 | 99312f10-e529-4bc1-b96c-543f6204d6f3 ==============================
[0m06:40:55.582171 [info ] [MainThread]: Running with dbt=1.7.10
[0m06:40:55.588429 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\cmotte\\.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt test', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m06:40:55.588429 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\cmotte\dbt_for_dvf\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m06:40:55.591945 [debug] [MainThread]: Command `dbt test` failed at 06:40:55.591945 after 0.27 seconds
[0m06:40:55.591945 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002275A2C2480>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002275A0134A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002275A39E570>]}
[0m06:40:55.594924 [debug] [MainThread]: Flushing usage events
[0m06:40:55.607644 [debug] [MainThread]: Error sending anonymous usage statistics. Disabling tracking for this execution. If you wish to permanently disable tracking, see: https://docs.getdbt.com/reference/global-configs#send-anonymous-usage-stats.
